//! Generates a vector fixture of the context corpus
//! (`context_corpus_vectors_<model>.json`) from the texts
//! `export_embedding_texts` writes. The model folder holds either a Model2Vec
//! model (`potion-multilingual-128M`) or a BERT encoder run by Candle
//! (`multilingual-e5-small`: mean pooling, "query: " and "passage: "
//! prefixes, as its model card asks). Vectors are
//! L2-normalized and stored as hex of `i8` (value × 127), which keeps cosine
//! within about 0.01 of `f32` at a quarter of the size.
//!
//! ```text
//! cargo run --release -j4 -- <model folder> <texts.json> <fixture.json>
//! ```

use std::path::Path;
use std::time::Instant;

use candle_core::{DType, Device, Tensor};
use candle_nn::VarBuilder;
use candle_transformers::models::bert::{BertModel, Config};
use model2vec_rs::model::StaticModel;
use serde_json::{json, Map, Value};
use tokenizers::Tokenizer;

enum Encoder {
    Static(StaticModel),
    Bert(BertModel, Tokenizer),
}

impl Encoder {
    fn load(folder: &Path) -> Self {
        let config = std::fs::read_to_string(folder.join("config.json")).expect("config.json");
        if config.contains("\"model2vec\"") {
            let model =
                StaticModel::from_pretrained(folder, None, Some(true), None).expect("model");
            return Self::Static(model);
        }
        let config: Config = serde_json::from_str(&config).expect("BERT config");
        let tokenizer = Tokenizer::from_file(folder.join("tokenizer.json")).expect("tokenizer");
        let weights = folder.join("model.safetensors");
        // SAFETY: the weights file is not modified while the generator runs.
        let vb =
            unsafe { VarBuilder::from_mmaped_safetensors(&[weights], DType::F32, &Device::Cpu) }
                .expect("weights");
        Self::Bert(BertModel::load(vb, &config).expect("BERT"), tokenizer)
    }

    /// An L2-normalized vector; `role` is "query" or "passage".
    fn encode(&self, role: &str, text: &str) -> Vec<f32> {
        let (model, tokenizer) = match self {
            Self::Static(model) => return model.encode_single(text),
            Self::Bert(model, tokenizer) => (model, tokenizer),
        };
        let encoding = tokenizer
            .encode(format!("{role}: {text}"), true)
            .expect("tokenize");
        let ids = Tensor::new(encoding.get_ids(), &Device::Cpu)
            .and_then(|ids| ids.unsqueeze(0))
            .expect("ids");
        let types = ids.zeros_like().expect("type ids");
        let hidden = model.forward(&ids, &types, None).expect("forward");
        let pooled = hidden
            .mean(1)
            .and_then(|t| t.squeeze(0))
            .expect("mean pool");
        let vector: Vec<f32> = pooled.to_vec1().expect("vector");
        let norm = vector.iter().map(|x| x * x).sum::<f32>().sqrt();
        vector.iter().map(|x| x / norm).collect()
    }
}

fn hex(vector: &[f32]) -> String {
    vector
        .iter()
        .map(|value| {
            format!(
                "{:02x}",
                (value * 127.0).round().clamp(-127.0, 127.0) as i8 as u8
            )
        })
        .collect()
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let [_, model_path, texts_path, output_path] = args.as_slice() else {
        panic!("usage: context-embeddings <model folder> <texts.json> <fixture.json>");
    };

    let start = Instant::now();
    let model = Encoder::load(Path::new(model_path));
    let load_ms = start.elapsed().as_millis();

    let texts: Value =
        serde_json::from_str(&std::fs::read_to_string(texts_path).expect("texts")).expect("json");
    let mut items = Map::new();
    for (alias, text) in texts["items"].as_object().expect("items") {
        let vector = model.encode("passage", text.as_str().expect("item text"));
        items.insert(alias.clone(), hex(&vector).into());
    }

    // One task at a time, as a prompt arrives, to time the per-task cost.
    let mut tasks = Map::new();
    let mut latency = Vec::new();
    for task in texts["tasks"].as_array().expect("tasks") {
        let task = task.as_str().expect("task");
        let start = Instant::now();
        let vector = model.encode("query", task);
        latency.push(start.elapsed().as_micros());
        tasks.insert(task.to_string(), hex(&vector).into());
    }
    latency.sort_unstable();

    let name = Path::new(model_path)
        .file_name()
        .map_or_else(String::new, |name| name.to_string_lossy().into_owned());
    let fixture = json!({
        "model": name,
        "note": concat!(
            "Generated by tools/context-embeddings from export_embedding_texts; ",
            "never edited by hand."
        ),
        "items": items,
        "tasks": tasks,
    });
    std::fs::write(
        output_path,
        serde_json::to_string_pretty(&fixture).expect("json"),
    )
    .expect("write fixture");
    println!(
        "load_ms={load_ms} tasks={} encode_p50_us={} encode_p95_us={}",
        latency.len(),
        latency[latency.len() / 2],
        latency[latency.len() * 95 / 100]
    );
}
