//! Generates `context_corpus_vectors.json`, the vector fixture of the context
//! corpus, from the texts `export_embedding_texts` writes. Vectors are
//! L2-normalized and stored as hex of `i8` (value × 127), which keeps cosine
//! within about 0.01 of `f32` at a quarter of the size.
//!
//! ```text
//! cargo run --release -j4 -- <model folder> <texts.json> <fixture.json>
//! ```

use std::time::Instant;

use model2vec_rs::model::StaticModel;
use serde_json::{json, Map, Value};

fn hex(vector: &[f32]) -> String {
    vector
        .iter()
        .map(|value| {
            format!(
                "{:02x}",
                (value * 127.0).round().clamp(-127.0, 127.0) as i8 as u8
            )
        })
        .collect()
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let [_, model_path, texts_path, output_path] = args.as_slice() else {
        panic!("usage: context-embeddings <model folder> <texts.json> <fixture.json>");
    };

    let start = Instant::now();
    let model = StaticModel::from_pretrained(model_path, None, Some(true), None).expect("model");
    let load_ms = start.elapsed().as_millis();

    let texts: Value =
        serde_json::from_str(&std::fs::read_to_string(texts_path).expect("texts")).expect("json");
    let mut items = Map::new();
    for (alias, text) in texts["items"].as_object().expect("items") {
        let vector = model.encode_single(text.as_str().expect("item text"));
        items.insert(alias.clone(), hex(&vector).into());
    }

    // One task at a time, as a prompt arrives, to time the per-task cost.
    let mut tasks = Map::new();
    let mut latency = Vec::new();
    for task in texts["tasks"].as_array().expect("tasks") {
        let task = task.as_str().expect("task");
        let start = Instant::now();
        let vector = model.encode_single(task);
        latency.push(start.elapsed().as_micros());
        tasks.insert(task.to_string(), hex(&vector).into());
    }
    latency.sort_unstable();

    let name = std::path::Path::new(model_path)
        .file_name()
        .map_or_else(String::new, |name| name.to_string_lossy().into_owned());
    let fixture = json!({
        "model": format!("minishlab/{name}"),
        "note": concat!(
            "Generated by tools/context-embeddings from export_embedding_texts; ",
            "never edited by hand."
        ),
        "items": items,
        "tasks": tasks,
    });
    std::fs::write(
        output_path,
        serde_json::to_string_pretty(&fixture).expect("json"),
    )
    .expect("write fixture");
    println!(
        "load_ms={load_ms} tasks={} encode_p50_us={} encode_p95_us={}",
        latency.len(),
        latency[latency.len() / 2],
        latency[latency.len() * 95 / 100]
    );
}
