//! Explicitly invoked: asks the live, consented provider which components of
//! the link corpus map each decision governs and writes the raw answers as the
//! fixture of the link quality gate (`storage-sqlite/tests/link_corpus.rs`).
//!
//! The model sees what production sends: the production prompt and request,
//! batched like the job (`BATCH_SIZE` decisions per call, in corpus order),
//! never the labels. The fixture keeps the entry of each decision from the
//! batched answer; the gate parses each with the per-decision production
//! validation, so a change of the checks is measured without calling the
//! model again. The corpus has 20 decisions: two calls.

#[path = "../../storage-sqlite/tests/fixtures/link_corpus.rs"]
#[allow(dead_code)]
mod corpus;

use std::collections::{BTreeMap, BTreeSet};
use std::sync::Arc;

use application::analysis::ExtractorFactory;
use application::batching::{answers, BATCH_SIZE};
use application::link_suggestions::{candidate_components, link_request, link_schema, LINK_PROMPT};
use application::output_language::OutputLanguage;
use application::overview::StructuredModel;
use application::paths::AppPaths;
use application::profile::{AiSettings, FileProfileStore};

#[test]
#[ignore = "calls the live provider; requires explicit user authorization"]
fn generate_link_corpus_answers() {
    let paths = AppPaths::from_env();
    let authorized =
        std::path::Path::new(r"C:\Users\Pablo\AppData\Local\xemnas\settings\ai-profile.json");
    assert_eq!(paths.ai_profile, authorized, "live profile path only");

    let settings = AiSettings::new(
        FileProfileStore::new(paths.ai_profile),
        ai_provider::KeyringSecretStore::new(),
    );
    let profile = settings.load_or_seed().expect("profile");
    let secret = settings
        .secret(&profile.credential_account())
        .expect("secret store")
        .unwrap_or_default();
    let factory =
        ai_provider::ProviderFactory::new(Arc::new(ai_provider::ChatGptSession::default()));
    let model = factory
        .authorized(&profile, secret, &settings)
        .expect("authorized provider");

    let entities = corpus::entities();
    let components = candidate_components(&entities);
    let mut answers_by_key = BTreeMap::new();
    let mut calls = 0;
    for batch in corpus::DECISIONS.chunks(BATCH_SIZE) {
        let subjects: Vec<_> = batch.iter().map(corpus::subject).collect();
        let subjects: Vec<_> = subjects.iter().collect();
        let request = link_request(
            OutputLanguage::ENGLISH,
            &subjects,
            &components,
            &BTreeSet::new(),
        );
        let answer = model
            .complete(LINK_PROMPT, &request, "decision_links", &link_schema())
            .expect("provider answer");
        calls += 1;
        let entries =
            answers::<serde_json::Value>(&answer, batch.len()).expect("a readable batched answer");
        for (decision, entry) in batch.iter().zip(entries) {
            let entry = entry.map_or_else(|| "{}".to_string(), |entry| entry.to_string());
            answers_by_key.insert(decision.0.to_string(), entry);
        }
    }
    println!("provider calls: {calls}");

    let fixture = serde_json::json!({
        "note": "Generated by ai-provider/tests/link_suggestions_live.rs with \
                 application::link_suggestions::LINK_PROMPT, BATCH_SIZE decisions per call, in \
                 the order of fixtures/link_corpus.rs; each answer is the model's entry for \
                 that decision; never edited by hand.",
        "model": profile.model,
        "answers": answers_by_key,
    });
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../storage-sqlite/tests/fixtures/link_corpus_answers.json"
    );
    std::fs::write(
        path,
        serde_json::to_string_pretty(&fixture).expect("json") + "\n",
    )
    .expect("write fixture");
    println!("{}", serde_json::to_string_pretty(&fixture).expect("json"));
}
