//! Explicitly invoked: asks the live, consented provider which components of
//! the link corpus map each decision governs and writes the raw answers as the
//! fixture of the link quality gate (`storage-sqlite/tests/link_corpus.rs`).
//!
//! The model sees what production sends: the production prompt and request,
//! one call per decision, never the labels. The gate parses these answers
//! with the production validation, so a change of the checks is measured
//! without calling the model again.

#[path = "../../storage-sqlite/tests/fixtures/link_corpus.rs"]
#[allow(dead_code)]
mod corpus;

use std::collections::BTreeMap;
use std::sync::Arc;

use application::analysis::ExtractorFactory;
use application::link_suggestions::{candidate_components, link_request, link_schema, LINK_PROMPT};
use application::overview::StructuredModel;
use application::paths::AppPaths;
use application::profile::{AiSettings, FileProfileStore};

#[test]
#[ignore = "calls the live provider; requires explicit user authorization"]
fn generate_link_corpus_answers() {
    let paths = AppPaths::from_env();
    let authorized =
        std::path::Path::new(r"C:\Users\Pablo\AppData\Local\xemnas\settings\ai-profile.json");
    assert_eq!(paths.ai_profile, authorized, "live profile path only");

    let settings = AiSettings::new(
        FileProfileStore::new(paths.ai_profile),
        ai_provider::KeyringSecretStore::new(),
    );
    let profile = settings.load_or_seed().expect("profile");
    let secret = settings
        .secret(&profile.credential_account())
        .expect("secret store")
        .unwrap_or_default();
    let factory =
        ai_provider::ProviderFactory::new(Arc::new(ai_provider::ChatGptSession::default()));
    let model = factory
        .authorized(&profile, secret, &settings)
        .expect("authorized provider");

    let entities = corpus::entities();
    let components = candidate_components(&entities);
    let mut answers = BTreeMap::new();
    for decision in corpus::DECISIONS {
        let request = link_request(&corpus::subject(decision), &components);
        let answer = model
            .complete(LINK_PROMPT, &request, "decision_links", &link_schema())
            .expect("provider answer");
        answers.insert(decision.0.to_string(), answer);
    }

    let fixture = serde_json::json!({
        "note": "Generated by ai-provider/tests/link_suggestions_live.rs with \
                 application::link_suggestions::LINK_PROMPT, one call per decision of \
                 fixtures/link_corpus.rs, raw answers; never edited by hand.",
        "model": profile.model,
        "answers": answers,
    });
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../storage-sqlite/tests/fixtures/link_corpus_answers.json"
    );
    std::fs::write(
        path,
        serde_json::to_string_pretty(&fixture).expect("json") + "\n",
    )
    .expect("write fixture");
    println!("{}", serde_json::to_string_pretty(&fixture).expect("json"));
}
