//! Explicitly invoked: asks the live, consented provider for the search terms
//! of the context corpus decisions and writes them as the corpus fixture.
//!
//! The model sees only each decision as stored (question, choice, rationale),
//! in production batches with the production prompt, never the corpus
//! queries; the context quality gate then measures with these terms.

#[path = "../../storage-sqlite/tests/fixtures/context_corpus.rs"]
#[allow(dead_code)]
mod corpus;

use std::collections::BTreeMap;
use std::sync::Arc;

use application::analysis::ExtractorFactory;
use application::overview::StructuredModel;
use application::paths::AppPaths;
use application::profile::{AiSettings, FileProfileStore};
use application::search_terms::{
    parse_search_terms, search_terms_request, search_terms_schema, TermSubject, BATCH,
    SEARCH_TERMS_PROMPT,
};

/// Rationale the corpus stores for a decision (`support::decision` and the
/// one revision in `context_corpus.rs`).
fn rationale(alias: &str) -> String {
    if alias == "override" {
        return concat!(
            "Override não deve zerar contadores nem mudar o comportamento local. ",
            "A avaliação é sintética e local; não representa aprovação de mantenedores."
        )
        .into();
    }
    format!("motivo de {alias}")
}

#[test]
#[ignore = "calls the live provider; requires explicit user authorization"]
fn generate_context_corpus_terms() {
    let paths = AppPaths::from_env();
    let authorized =
        std::path::Path::new(r"C:\Users\Pablo\AppData\Local\xemnas\settings\ai-profile.json");
    assert_eq!(paths.ai_profile, authorized, "live profile path only");

    let settings = AiSettings::new(
        FileProfileStore::new(paths.ai_profile),
        ai_provider::KeyringSecretStore::new(),
    );
    let profile = settings.load_or_seed().expect("profile");
    let secret = settings
        .secret(&profile.credential_account())
        .expect("secret store")
        .unwrap_or_default();
    let factory =
        ai_provider::ProviderFactory::new(Arc::new(ai_provider::ChatGptSession::default()));
    let model = factory
        .authorized(&profile, secret, &settings)
        .expect("authorized provider");

    let subjects: Vec<(String, TermSubject)> = corpus::DECISIONS
        .iter()
        .filter(|(_, project, _, _)| *project == "p1")
        .map(|(alias, _, question, choice)| {
            (
                alias.to_string(),
                TermSubject {
                    decision_id: alias.to_string(),
                    question: question.to_string(),
                    choice: choice.to_string(),
                    rationale: rationale(alias),
                },
            )
        })
        .collect();

    let mut terms = BTreeMap::new();
    for batch in subjects.chunks(BATCH) {
        let batch: Vec<TermSubject> = batch.iter().map(|(_, subject)| subject.clone()).collect();
        let answer = model
            .complete(
                SEARCH_TERMS_PROMPT,
                &search_terms_request(&batch),
                "decision_search_terms",
                &search_terms_schema(),
            )
            .expect("provider answer");
        let parsed = parse_search_terms(&answer, &batch).expect("readable answer");
        for (subject, found) in batch.iter().zip(parsed) {
            terms.insert(subject.decision_id.clone(), found);
        }
    }

    let fixture = serde_json::json!({
        "note": "Generated by ai-provider/tests/search_terms_live.rs from each decision's \
                 stored text only, with application::search_terms::SEARCH_TERMS_PROMPT; \
                 never edited by hand.",
        "model": profile.model,
        "terms": terms,
    });
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../storage-sqlite/tests/fixtures/context_corpus_terms.json"
    );
    std::fs::write(
        path,
        serde_json::to_string_pretty(&fixture).expect("json") + "\n",
    )
    .expect("write fixture");
    println!("{}", serde_json::to_string_pretty(&fixture).expect("json"));
}
