//! Search terms of an adopted decision: the words someone would type to
//! find it that its own text does not use (document expansion, doc2query).
//!
//! A task written as "adicionar uma coluna no banco" shares no word with
//! "Como evoluir o esquema do banco?"; the decision's terms ("coluna",
//! "tabela", "schema") close that gap once, when the decision is adopted,
//! instead of costing a model call on every prompt. They go to their own
//! column of the full-text index and are a last resort of the Context Pack:
//! they count only when no decision speaks of the task in its own words.
//!
//! Generated terms can be invented: a term that names a tool or value the
//! decision never mentions pulls it into unrelated tasks. The prompt forbids
//! that, the parser keeps at most [`MAX_TERMS`] short ones and drops what
//! the decision already says, and the context quality gate measures the
//! effect with terms generated by a real model from the decision text only.

use std::collections::BTreeSet;

use serde::Deserialize;
use serde_json::json;

use crate::analysis::ExtractorFactory;
use crate::clock::now_rfc3339;
use crate::jobs::{JobRecord, JobRepository, JobState};
use crate::overview::StructuredModel;
use crate::profile::{choose_extractor, AiSettings, ExtractorChoice, ProfileStore, SecretStore};

/// Job kind that writes the search terms of a project's decisions.
pub const SEARCH_TERMS_JOB_KIND: &str = crate::jobs::JobKind::DeriveSearchTerms.as_str();
/// Queued term jobs that run together as one: they are the same work.
pub const MAX_COALESCED_JOBS: usize = 100;
/// Terms kept per decision, at most.
pub const MAX_TERMS: usize = 8;
/// Decisions sent in one call: the same batch size as the other job kinds.
/// This kind was already batched: its job is per project, not per decision.
pub const BATCH: usize = crate::batching::BATCH_SIZE;
/// Longest term accepted, in characters.
const MAX_TERM_CHARS: usize = 40;
/// Most words in one term.
const MAX_TERM_WORDS: usize = 3;
/// Characters of a rationale sent to the model.
const MAX_RATIONALE_CHARS: usize = 600;

/// Instructions shared by the job and by the evaluation fixture.
pub const SEARCH_TERMS_PROMPT: &str = "You index engineering decisions of a software \
project so a coding agent finds them. For each decision, list up to 8 short search terms \
(1 to 3 words each) that someone would type to find it and that its text does not already \
use: synonyms, the same idea in the other language (Portuguese or English), acronyms and \
their expansions, and the common names of what it is about. Only terms about what the \
decision itself says: never names of tools, libraries, products, numbers or values that \
the decision does not mention, and nothing about other decisions. Answer only JSON: \
{\"decisions\":[{\"id\":\"1\",\"terms\":[\"...\"]}]}, one entry per decision id.";

/// A decision as the model sees it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TermSubject {
    /// Decision id; never sent, the model sees a position.
    pub decision_id: String,
    /// The question.
    pub question: String,
    /// The choice.
    pub choice: String,
    /// The rationale.
    pub rationale: String,
}

/// Failures of the job.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SearchTermError {
    /// Storage failed.
    Storage(String),
    /// The provider failed.
    Provider(String),
    /// The provider asked for a pause or timed out; the job is requeued.
    Deferred(Option<std::time::Duration>),
}

impl std::fmt::Display for SearchTermError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Storage(detail) => write!(formatter, "storage: {detail}"),
            Self::Provider(detail) => write!(formatter, "provedor: {detail}"),
            Self::Deferred(_) => formatter.write_str("provedor: pausa pedida"),
        }
    }
}

impl std::error::Error for SearchTermError {}

fn storage(error: impl std::fmt::Display) -> SearchTermError {
    SearchTermError::Storage(error.to_string())
}

/// Persistence of search terms.
pub trait SearchTermStore {
    /// Adopted decisions of a project that were never given terms, oldest
    /// first.
    fn decisions_without_terms(
        &self,
        project_id: &str,
        limit: usize,
    ) -> Result<Vec<TermSubject>, String>;

    /// Records a decision's terms (possibly none, so it is not asked again)
    /// and puts them in the full-text index.
    fn set_search_terms(
        &self,
        decision_id: &str,
        terms: &[String],
        model: &str,
    ) -> Result<(), String>;
}

/// JSON schema of the answer.
pub fn search_terms_schema() -> serde_json::Value {
    json!({
        "type": "object",
        "additionalProperties": false,
        "required": ["decisions"],
        "properties": {
            "decisions": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": false,
                    "required": ["id", "terms"],
                    "properties": {
                        "id": { "type": "string" },
                        "terms": { "type": "array", "items": { "type": "string" } }
                    }
                }
            }
        }
    })
}

/// The user message: decisions numbered from 1, secrets redacted.
pub fn search_terms_request(subjects: &[TermSubject]) -> String {
    let mut user = String::new();
    for (position, subject) in subjects.iter().enumerate() {
        user.push_str(&format!(
            "id: {}\nQuestion: {}\nChoice: {}\nWhy: {}\n\n",
            position + 1,
            crate::external::protected_text(&subject.question),
            crate::external::protected_text(&subject.choice),
            crate::external::limited_text(&subject.rationale, MAX_RATIONALE_CHARS)
        ));
    }
    user
}

#[derive(Deserialize)]
struct Answer {
    decisions: Vec<AnswerItem>,
}

#[derive(Deserialize)]
struct AnswerItem {
    id: String,
    #[serde(default)]
    terms: Vec<String>,
}

/// The terms the model gave each subject, in subject order, after the
/// checks; `None` when the answer cannot be read at all.
pub fn parse_search_terms(answer: &str, subjects: &[TermSubject]) -> Option<Vec<Vec<String>>> {
    let answer: Answer = serde_json::from_str(answer).ok()?;
    let mut out = vec![Vec::new(); subjects.len()];
    for item in answer.decisions {
        let Some(index) = item
            .id
            .trim()
            .parse::<usize>()
            .ok()
            .and_then(|id| id.checked_sub(1))
            .filter(|index| *index < subjects.len())
        else {
            continue;
        };
        out[index] = clean_terms(&item.terms, &subjects[index]);
    }
    Some(out)
}

/// Short, distinct terms that add a word the decision does not have.
fn clean_terms(terms: &[String], subject: &TermSubject) -> Vec<String> {
    let own = words(&format!(
        "{} {} {}",
        subject.question, subject.choice, subject.rationale
    ));
    let mut seen = BTreeSet::new();
    terms
        .iter()
        .map(|term| term.split_whitespace().collect::<Vec<_>>().join(" "))
        .filter(|term| {
            !term.is_empty()
                && term.chars().count() <= MAX_TERM_CHARS
                && term.split(' ').count() <= MAX_TERM_WORDS
                && !term.chars().any(char::is_control)
        })
        .filter(|term| !words(term).is_subset(&own))
        .filter(|term| seen.insert(crate::terms::fold(term)))
        .take(MAX_TERMS)
        .collect()
}

fn words(text: &str) -> BTreeSet<String> {
    text.split(|character: char| !(character.is_alphanumeric() || character == '_'))
        .filter(|word| !word.is_empty())
        .map(crate::terms::fold)
        .collect()
}

/// Queues the job that gives a project's decisions their terms. It is
/// idempotent: a run with nothing left to do makes no call.
pub fn queue_search_terms<S: JobRepository>(store: &S, project_id: &str) {
    let now = now_rfc3339();
    // Terms are an aid to search; nothing waits on them.
    let _ = JobRepository::insert(
        store,
        &JobRecord {
            id: uuid::Uuid::now_v7().to_string(),
            kind: SEARCH_TERMS_JOB_KIND.to_string(),
            payload: project_id.to_string(),
            state: JobState::Queued,
            idempotent: true,
            attempts: 0,
            last_error: None,
            created_at: now.clone(),
            updated_at: now,
        },
    );
}

/// The job: one call per batch of decisions without terms.
pub struct SearchTermFinder<S, P, K, F> {
    store: S,
    settings: AiSettings<P, K>,
    factory: F,
}

impl<S, P, K, F> SearchTermFinder<S, P, K, F>
where
    S: SearchTermStore + JobRepository,
    P: ProfileStore,
    K: SecretStore,
    F: ExtractorFactory,
    F::Extractor: StructuredModel,
{
    /// Wraps the store, the AI settings and the provider factory.
    pub fn new(store: S, settings: AiSettings<P, K>, factory: F) -> Self {
        Self {
            store,
            settings,
            factory,
        }
    }

    /// Runs [`SearchTermFinder::run`] once for each distinct project of
    /// `project_ids`, one result per entry: the queued jobs of a project (one
    /// per adoption) are the same work, so they share one run.
    pub fn run_projects(&self, project_ids: &[&str]) -> Vec<Result<usize, SearchTermError>> {
        let mut done: Vec<(&str, Result<usize, SearchTermError>)> = Vec::new();
        project_ids
            .iter()
            .map(|project| {
                if let Some((_, result)) = done.iter().find(|(known, _)| known == project) {
                    // The run already took every decision it could.
                    return result.clone().map(|_| 0);
                }
                let result = self.run(project);
                done.push((project, result.clone()));
                result
            })
            .collect()
    }

    /// Writes terms for up to [`BATCH`] decisions of the project and queues
    /// another run when more remain; 0 without an enabled provider.
    ///
    /// # Errors
    ///
    /// `storage`, or `provider` when the call fails.
    pub fn run(&self, project_id: &str) -> Result<usize, SearchTermError> {
        let subjects = self
            .store
            .decisions_without_terms(project_id, BATCH + 1)
            .map_err(storage)?;
        if subjects.is_empty() {
            return Ok(0);
        }
        let more = subjects.len() > BATCH;
        let subjects = &subjects[..subjects.len().min(BATCH)];
        let profile = self.settings.load_or_seed().map_err(storage)?;
        if choose_extractor(Some(&profile)) != ExtractorChoice::ExternalEnabled {
            return Ok(0);
        }
        let secret = match self.settings.secret(&profile.credential_account()) {
            Ok(Some(secret)) => secret,
            Ok(None) if !profile.credential_required() => String::new(),
            _ => return Ok(0),
        };
        let Ok(model) = self.factory.authorized(&profile, secret, &self.settings) else {
            return Ok(0);
        };
        let answer = model
            .complete(
                SEARCH_TERMS_PROMPT,
                &search_terms_request(subjects),
                "decision_search_terms",
                &search_terms_schema(),
            )
            .map_err(|error| match error.job_failure() {
                crate::jobs::JobFailure::Deferred { retry_after } => {
                    SearchTermError::Deferred(retry_after)
                }
                crate::jobs::JobFailure::Failed => SearchTermError::Provider(error.to_string()),
            })?;
        let Some(terms) = parse_search_terms(&answer, subjects) else {
            return Err(SearchTermError::Provider("resposta ilegível".into()));
        };
        for (subject, terms) in subjects.iter().zip(&terms) {
            self.store
                .set_search_terms(&subject.decision_id, terms, &profile.model)
                .map_err(storage)?;
        }
        if more {
            queue_search_terms(&self.store, project_id);
        }
        Ok(subjects.len())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn subject(question: &str, choice: &str) -> TermSubject {
        TermSubject {
            decision_id: "d".into(),
            question: question.into(),
            choice: choice.into(),
            rationale: String::new(),
        }
    }

    #[test]
    fn terms_add_words_and_stay_short() {
        let subjects = [
            subject(
                "Como evoluir o esquema do banco?",
                "Migrações só para frente",
            ),
            subject("O que o CI verifica?", "fmt e clippy"),
        ];
        let answer = r#"{"decisions":[
            {"id":"1","terms":["schema migration","coluna","Esquema do banco","coluna",
              "um termo comprido demais para caber aqui de jeito nenhum","a b c d"]},
            {"id":"2","terms":["integração contínua","pipeline"]},
            {"id":"9","terms":["fora"]}
        ]}"#;
        let terms = parse_search_terms(answer, &subjects).unwrap();
        assert_eq!(terms[0], vec!["schema migration", "coluna"]);
        assert_eq!(terms[1], vec!["integração contínua", "pipeline"]);
        assert!(parse_search_terms("{", &subjects).is_none());
    }

    #[test]
    fn a_long_answer_keeps_at_most_eight() {
        let subjects = [subject("Pergunta", "Escolha")];
        let many: Vec<String> = (0..20).map(|n| format!("termo{n}")).collect();
        let answer = json!({"decisions":[{"id":"1","terms":many}]}).to_string();
        assert_eq!(
            parse_search_terms(&answer, &subjects).unwrap()[0].len(),
            MAX_TERMS
        );
    }

    #[test]
    fn the_request_numbers_decisions_and_hides_ids() {
        let request = search_terms_request(&[subject("Q1", "C1"), subject("Q2", "C2")]);
        assert!(request.contains("id: 1\nQuestion: Q1"));
        assert!(request.contains("id: 2\nQuestion: Q2"));
        assert!(!request.contains("id: d"));
    }
}
