//! Capture Envelope construction and schema validation.
//!
//! Builds the versioned wire shape described in MVP-SPEC §10 from a user turn
//! and its child responses/diff, then validates it against the versioned JSON
//! Schema (`schemas/capture-envelope.schema.json`) before it is sent. The schema
//! is generated by Rust and is the single source of truth; this module only
//! shapes data into it.
//!
//! Fingerprints are the lowercase SHA-256 of the UTF-8 content, byte-for-byte
//! the same algorithm as `integration_contracts::artifact_fingerprint`.

import { createHash, randomBytes } from "node:crypto";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";

import type { AnySchemaObject } from "ajv";
import { Ajv2020 } from "ajv/dist/2020.js";
import type { FormatsPlugin } from "ajv-formats";

import { adapterVersion, packageRoot } from "./config.js";
import type { OpenCodeFileDiff, OpenCodeMessage } from "./opencode.js";
import {
  boundContent,
  collectText,
  omitReasoningParts,
  reduceDiffs,
  reducePatches,
} from "./redact.js";

/** The only capture contract version this adapter emits. */
export const CAPTURE_SCHEMA_VERSION = 1;

/** Artifact kinds recognised by the contract (MVP-SPEC §10). */
export type ArtifactKind =
  | "user_text"
  | "assistant_text"
  | "diff_hunk"
  | "tool_summary";

/** One artifact inside a capture envelope. */
export interface EnvelopeArtifact {
  artifact_id: string;
  kind: ArtifactKind;
  content: string;
  metadata: Record<string, unknown>;
  fingerprint: string;
}

/** The versioned Capture Envelope. */
export interface CaptureEnvelope {
  schema_version: number;
  capture_id: string;
  idempotency_key: string;
  source: {
    adapter: string;
    adapter_version: string;
    session_id: string;
    message_id: string;
  };
  project: { canonical_path: string };
  observed_at: string;
  artifacts: EnvelopeArtifact[];
}

/** Limits applied while building an envelope. */
export interface EnvelopeLimits {
  maxArtifactBytes: number;
  maxArtifacts: number;
  maxDiffBytes: number;
}

/** Inputs for one user turn. */
export interface BuildEnvelopeInput {
  sessionId: string;
  directory: string;
  userMessage: OpenCodeMessage;
  assistantMessages: OpenCodeMessage[];
  diffs: OpenCodeFileDiff[];
  limits: EnvelopeLimits;
  now?: Date;
}

/** Returns the lowercase SHA-256 hex of `value` encoded as UTF-8. */
export function sha256Hex(value: string): string {
  return createHash("sha256").update(value, "utf8").digest("hex");
}

/**
 * Generates a UUID v7 string.
 *
 * The 48-bit millisecond timestamp occupies the high bits, then the version and
 * RFC 4122 variant nibbles are set. `node:crypto` only offers v4, so v7 is built
 * from random bytes without a new dependency.
 */
export function uuidv7(
  nowMs: number = Date.now(),
  random: (size: number) => Buffer = randomBytes,
): string {
  const bytes = random(16);
  const timestamp = BigInt(nowMs);
  bytes[0] = Number((timestamp >> 40n) & 0xffn);
  bytes[1] = Number((timestamp >> 32n) & 0xffn);
  bytes[2] = Number((timestamp >> 24n) & 0xffn);
  bytes[3] = Number((timestamp >> 16n) & 0xffn);
  bytes[4] = Number((timestamp >> 8n) & 0xffn);
  bytes[5] = Number(timestamp & 0xffn);
  bytes[6] = (bytes[6] & 0x0f) | 0x70;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  const hex = bytes.toString("hex");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/** Deterministic raw diff text used for the idempotency key's `diff_hash`. */
function assembleRawDiff(diffs: OpenCodeFileDiff[]): string {
  // NUL/unit separators keep the hash stable and unambiguous without leaking
  // the diff itself into the key material.
  return diffs
    .map((diff) => `${diff.file}\u0000${diff.before}\u0000${diff.after}`)
    .join("\u0001");
}

/**
 * Builds the envelope for one user turn, or `null` when nothing survives
 * redaction and bounding (an envelope must carry at least one artifact).
 */
export function buildEnvelope(input: BuildEnvelopeInput): CaptureEnvelope | null {
  const artifacts: EnvelopeArtifact[] = [];

  const pushArtifact = (
    kind: ArtifactKind,
    content: string,
    metadata: Record<string, unknown>,
  ): void => {
    if (content.length === 0 || artifacts.length >= input.limits.maxArtifacts) {
      return;
    }
    artifacts.push({
      artifact_id: uuidv7(),
      kind,
      content,
      metadata,
      fingerprint: sha256Hex(content),
    });
  };

  const userParts = omitReasoningParts(input.userMessage.parts);
  pushArtifact(
    "user_text",
    boundContent(collectText(userParts), input.limits.maxArtifactBytes),
    {},
  );

  const assistantParts = input.assistantMessages.flatMap((message) =>
    omitReasoningParts(message.parts),
  );
  pushArtifact(
    "assistant_text",
    boundContent(collectText(assistantParts), input.limits.maxArtifactBytes),
    {},
  );

  // The session diff route is normally empty for the turn just finished
  // (OpenCode computes it before the model edits); the edit tools' own
  // patches are the fallback.
  const patches = assistantParts.flatMap((part) =>
    part.patch === undefined ? [] : [part.patch],
  );
  const reducedDiffs =
    input.diffs.length > 0
      ? reduceDiffs(input.diffs, input.limits.maxDiffBytes)
      : reducePatches(patches, input.directory, input.limits.maxDiffBytes);
  for (const reduced of reducedDiffs) {
    pushArtifact("diff_hunk", reduced.content, { file: reduced.file });
  }

  for (const part of assistantParts) {
    if (part.type !== "tool" || typeof part.tool !== "string") {
      continue;
    }
    const status = part.state?.status ?? "unknown";
    pushArtifact(
      "tool_summary",
      boundContent(
        JSON.stringify({ tool: part.tool, status }),
        input.limits.maxArtifactBytes,
      ),
      { tool: part.tool, status },
    );
  }

  if (artifacts.length === 0) {
    return null;
  }

  const diffHash = sha256Hex(
    input.diffs.length > 0
      ? assembleRawDiff(input.diffs)
      : patches.map((patch) => `${patch.file}\u0000${patch.diff}`).join("\u0001"),
  );
  const observedAt = (input.now ?? new Date()).toISOString();

  return {
    schema_version: CAPTURE_SCHEMA_VERSION,
    capture_id: uuidv7(),
    idempotency_key: `opencode:${input.sessionId}:${input.userMessage.id}:${diffHash}`,
    source: {
      adapter: "opencode",
      adapter_version: adapterVersion(),
      session_id: input.sessionId,
      message_id: input.userMessage.id,
    },
    project: { canonical_path: input.directory },
    observed_at: observedAt,
    artifacts,
  };
}

const require = createRequire(import.meta.url);
const addFormats = require("ajv-formats") as FormatsPlugin;

const schemaPath = join(packageRoot(), "schemas", "capture-envelope.schema.json");
const schemaDocument = JSON.parse(
  readFileSync(schemaPath, "utf8"),
) as AnySchemaObject;

// Draft 2020-12 with asserted formats, matching the Rust validator. Strict mode
// compiles the schemars-generated schema without relaxation.
const ajv = new Ajv2020({ validateFormats: true, strict: true });
addFormats(ajv);
const validate = ajv.compile(schemaDocument);

/** Result of validating an envelope; carries no instance content. */
export interface EnvelopeValidation {
  valid: boolean;
  errorCount: number;
}

/** Validates a value against the versioned capture schema. */
export function validateEnvelope(value: unknown): EnvelopeValidation {
  // The schema is not async, so the compiled validator always returns a
  // boolean here; the Ajv type widens to `boolean | Promise<unknown>`.
  const valid = validate(value) === true;
  return {
    valid,
    errorCount: valid ? 0 : (validate.errors?.length ?? 0),
  };
}
